KSB-3-5 tsk line from the server
Plyshkaa/KotlinSprintBot pull request #15
Opened 2024-04-27 09:04 UTC by Plyshkaa

2024-04-29 05:26 UTC, ievetrovdev requested changes

2024-04-29 05:26 UTC, ievetrovdev commented on src/main/kotlin/lesson_3/lesson3_task5.kt
> +    val parts = playerMove.split("-")
Мы пользуемся сплит и обрати внимание на его сигнатуру. метод имеет ключевое слово vararg - то есть он может принимать произвольное количество параметров. то есть в данном случае разделителей. Подробнее тут https://metanit.com/kotlin/tutorial/3.2.php

2024-04-29 19:17 UTC, Plyshkaa commented on src/main/kotlin/lesson_3/lesson3_task5.kt
> +    val parts = playerMove.split("-")
@ievetrovdev Извини, но не совсем понял проблему

Можешь пожалуйста дополнить что не так

2024-05-01 13:41 UTC, ievetrovdev approved these changes
Теперь все верно

2024-05-01 13:47 UTC, merged