KSB-4-4 fly to space task
Plyshkaa/KotlinSprintBot pull request #20
Opened 2024-04-30 03:45 UTC by Plyshkaa

2024-04-30 17:14 UTC, ievetrovdev requested changes

2024-04-30 17:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task5.kt
> +    val flyVer1 = (!damageShip && countCrew in 55..70 && countBox > 50) ||
Тут по аналогии с задачей про агрокомплекс, нужно вынести в константы переменные, с которыми сравнивается условие. Кроме того в этом коде они являются [магическими числами](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F). Не лучшая практика.

2024-04-30 17:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task5.kt
> +    val damageShip = readLine().toBoolean()
Рекомендуется Boolean переменные называть, "отвечая на вопрос“ да/нет. Ну и принято название начинать для них с is, в редких случаях has. Например, hasDamage, isDamaged.

2024-04-30 19:16 UTC, Plyshkaa commented
@ievetrovdev по поводу вынесения в переменные согласен, но не совсем понял почему константы? Кол-во экипажа и кол-во груза же может меняться

Мы выносим на сколько я понимаю мин и макс сколько может погрузить корабль?

2024-05-01 13:58 UTC, ievetrovdev requested changes

2024-05-01 13:58 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task5.kt
> +const val minCountBox = 50
Про стиль написания констант отписал ранее. Давай еще добавим в констаны наличие повреждений корпуса (Boolean);
благоприятность метеоусловий (Boolean).

Константы, потому что мы с ними сравниваем входные данные. Это критерии, они постоянные и не планируются изменяться после компиляции.

2024-05-02 18:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_4/lesson4_task5.kt
> +const val minCountBox = 50
> Про стиль написания констант отписал ранее. **Давай еще добавим в констаны наличие повреждений корпуса (Boolean); благоприятность метеоусловий (Boolean)**.
> 
> Константы, потому что мы с ними сравниваем входные данные. Это критерии, они постоянные и не планируются изменяться после компиляции.

Почему не добавил? соответствующие входные данные не с чем не сравниваются

2024-05-02 18:43 UTC, ievetrovdev requested changes
Тут смысл сравнить данные - как есть и как должно быть, добавь константы, плиз)

2024-05-03 06:01 UTC, Plyshkaa commented
@ievetrovdev делал в другой IDE и почему то коммиты не залетели, сейчас должно быть правильно

2024-05-03 18:30 UTC, ievetrovdev approved these changes
Отлично!

2024-05-03 18:31 UTC, merged