KSB-5-4 task Zaphod login
Plyshkaa/KotlinSprintBot pull request #24
Opened 2024-05-02 10:55 UTC by Plyshkaa

2024-05-03 07:14 UTC, ievetrovdev requested changes
Решение правильное, но попал лишний файл. Будь внимателнее. В робе такое может сломать проект

2024-05-03 07:18 UTC, Plyshkaa commented
@ievetrovdev а как правильнее будет такое фиксить? Удалять файл из проекта нет смысла же, комит тоже не поправлю, просто новый комит сделать с правильными файлом чтобы только он был ?

2024-05-04 13:58 UTC, ievetrovdev requested changes
Важны не сами кометы, сколько и что в них было, а итоговый результат который попадет в ПР. Так что нужно просто удалить файл и сделать еще один комит без него

2024-05-05 11:35 UTC, ievetrovdev approved these changes

2024-05-05 12:12 UTC, merged