KSB-2-3 arrival train
Plyshkaa/KotlinSprintBot pull request #7
Opened 2024-04-26 09:10 UTC by Plyshkaa

2024-04-27 14:41 UTC, ievetrovdev approved these changes

2024-04-27 14:41 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    val totalMinutesFromMidnight = trainExitHour * 60 + trainExitMinut + travelTime
Все окей, но сейчас значения в строке захардкожены. Такую программу сложно модифицировать, ведь мы предполагаем, что переменные инициализируются динамически разными значениями. Следует проинициализировать значения из ТЗ по отдельности.

Иными словами это [магические числ](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F)а, что не является хорошей практикой.

2024-04-27 15:03 UTC, Plyshkaa commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    val totalMinutesFromMidnight = trainExitHour * 60 + trainExitMinut + travelTime
@ievetrovdev Подскажи пожалуйста как понять, когда нужно выносить в константу, а когда простой переменной оставлять? 

Пользоваться логикой что входные данные могут измениться?

2024-04-28 07:21 UTC, ievetrovdev requested changes

2024-04-28 07:21 UTC, ievetrovdev commented on src/main/kotlin/lesson_2/lesson2_task3.kt
> +    val totalMinutesFromMidnight = trainExitHour * 60 + trainExitMinute + travelTime
Точного определения нету.
Можно определять константы это или нет так. Если эта переменная (число) при изменении сломает программу, то это константы. Если же при изменении ничего не случится и программа дальше будет работать то переменная.
В данном задание 9 39 457 это просто неизменяемые переменные, так как если изменить то просто будет считаться другое время. 60 и 24 это уже константы, так как при измени программа никогда не будет правильно работать

2024-04-28 14:16 UTC, ievetrovdev approved these changes

2024-04-28 14:35 UTC, merged